name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Docker image
        run: docker build -t node-app .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 node-app

      - name: Show running containers
        run: docker ps

      - name: Stop Docker container
        run: docker stop $(docker ps -q)
